(deffacts tressette-players-and-score
  (player-team (player p1) (team team1))
  (player-team (player p2) (team team2))
  (player-team (player p3) (team team1))
  (player-team (player p4) (team team2))
  (team-score (team team1) (points 0))
  (team-score (team team2) (points 0))
  (action-result (valid none) (code boot) (reason "Game initialized."))
  (game-state
    (phase setup)
    (hand-number 1)
    (dealer p1)
    (leader none)
    (current-player none)
    (trick-number 0)
    (target-score 21))
  (dealing (hand 1)))

(deffacts tressette-deck
  (deck-card (position 1) (suit denari) (rank three))
  (deck-card (position 2) (suit denari) (rank two))
  (deck-card (position 3) (suit denari) (rank ace))
  (deck-card (position 4) (suit denari) (rank king))
  (deck-card (position 5) (suit denari) (rank knight))
  (deck-card (position 6) (suit denari) (rank knave))
  (deck-card (position 7) (suit denari) (rank seven))
  (deck-card (position 8) (suit denari) (rank six))
  (deck-card (position 9) (suit denari) (rank five))
  (deck-card (position 10) (suit denari) (rank four))

  (deck-card (position 11) (suit coppe) (rank three))
  (deck-card (position 12) (suit coppe) (rank two))
  (deck-card (position 13) (suit coppe) (rank ace))
  (deck-card (position 14) (suit coppe) (rank king))
  (deck-card (position 15) (suit coppe) (rank knight))
  (deck-card (position 16) (suit coppe) (rank knave))
  (deck-card (position 17) (suit coppe) (rank seven))
  (deck-card (position 18) (suit coppe) (rank six))
  (deck-card (position 19) (suit coppe) (rank five))
  (deck-card (position 20) (suit coppe) (rank four))

  (deck-card (position 21) (suit spade) (rank three))
  (deck-card (position 22) (suit spade) (rank two))
  (deck-card (position 23) (suit spade) (rank ace))
  (deck-card (position 24) (suit spade) (rank king))
  (deck-card (position 25) (suit spade) (rank knight))
  (deck-card (position 26) (suit spade) (rank knave))
  (deck-card (position 27) (suit spade) (rank seven))
  (deck-card (position 28) (suit spade) (rank six))
  (deck-card (position 29) (suit spade) (rank five))
  (deck-card (position 30) (suit spade) (rank four))

  (deck-card (position 31) (suit bastoni) (rank three))
  (deck-card (position 32) (suit bastoni) (rank two))
  (deck-card (position 33) (suit bastoni) (rank ace))
  (deck-card (position 34) (suit bastoni) (rank king))
  (deck-card (position 35) (suit bastoni) (rank knight))
  (deck-card (position 36) (suit bastoni) (rank knave))
  (deck-card (position 37) (suit bastoni) (rank seven))
  (deck-card (position 38) (suit bastoni) (rank six))
  (deck-card (position 39) (suit bastoni) (rank five))
  (deck-card (position 40) (suit bastoni) (rank four)))
